-- Manual PostgreSQL migration for existing databases before validate startup.
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS webhook_signing_secret VARCHAR(256);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS external_transaction_id VARCHAR(255);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS related_transaction_id VARCHAR(64);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS case_id VARCHAR(64);
-- If old data contains duplicates, reconcile those references before applying.
CREATE UNIQUE INDEX IF NOT EXISTS uq_transactions_tenant_external
ON transactions(tenant_id, external_transaction_id);
CREATE TABLE IF NOT EXISTS webhook_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    payload TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    delivered_at TIMESTAMP WITH TIME ZONE,
    attempts INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_due
ON webhook_deliveries(next_attempt_at, created_at) WHERE delivered_at IS NULL;
